# Generated by Django 2.0.1 on 2019-09-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstClassify',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='一级分类id')),
                ('name', models.CharField(max_length=20, verbose_name='一级分类名')),
            ],
            options={
                'verbose_name': '一级分类表',
                'verbose_name_plural': '一级分类表',
                'db_table': 't_first_classcify',
            },
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='水果id')),
                ('goods_img', models.ImageField(blank=True, height_field='goods_img_height', null=True, upload_to='imags', verbose_name='商品图片', width_field='goods_img_width')),
                ('goods_img_width', models.IntegerField(null=True, verbose_name='宽')),
                ('goods_img_height', models.IntegerField(null=True, verbose_name='高')),
                ('name', models.CharField(max_length=20, verbose_name='水果名')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('sales_volume', models.IntegerField(verbose_name='销量')),
                ('storage', models.IntegerField(verbose_name='库存')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场价格')),
                ('produce_place', models.CharField(max_length=20, verbose_name='生产地')),
                ('detail_img', models.ImageField(blank=True, height_field='detail_img_height', null=True, upload_to='imags', verbose_name='详情页图片', width_field='detail_img_width')),
                ('detail_img_width', models.IntegerField(null=True, verbose_name='宽')),
                ('detail_img_height', models.IntegerField(null=True, verbose_name='高')),
                ('description', models.TextField(verbose_name='商品详情')),
                ('detail', models.TextField(verbose_name='详情')),
                ('is_selected', models.BooleanField(verbose_name='是否精选')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 't_goods',
            },
        ),
        migrations.CreateModel(
            name='SecClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='二级分类名')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.FirstClassify', verbose_name='二级分类id')),
            ],
            options={
                'verbose_name': '二级分类表',
                'verbose_name_plural': '二级分类表',
                'db_table': 't_sec_classcify',
            },
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='cate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.SecClassify', verbose_name='分类id'),
        ),
    ]
