# Generated by Django 2.0.1 on 2019-09-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='cate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goodsapp.SecClassify', verbose_name='分类id'),
        ),
        migrations.AlterField(
            model_name='secclassify',
            name='name',
            field=models.CharField(max_length=100, verbose_name='二级分类名'),
        ),
    ]
