# Generated by Django 2.0.1 on 2019-09-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsmodel',
            name='detail_img_height',
        ),
        migrations.RemoveField(
            model_name='goodsmodel',
            name='detail_img_width',
        ),
        migrations.RemoveField(
            model_name='goodsmodel',
            name='goods_img_height',
        ),
        migrations.RemoveField(
            model_name='goodsmodel',
            name='goods_img_width',
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='detail_img',
            field=models.CharField(max_length=200, null=True, verbose_name='详情页图片'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='goods_img',
            field=models.CharField(max_length=200, null=True, verbose_name='商品图片'),
        ),
    ]
