# Generated by Django 2.0.1 on 2019-09-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_auto_20190910_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='水果名'),
        ),
    ]
