# Generated by Django 2.0.1 on 2019-09-10 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_auto_20190910_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secclassify',
            name='id',
        ),
        migrations.RemoveField(
            model_name='secclassify',
            name='uid',
        ),
        migrations.AddField(
            model_name='secclassify',
            name='uid1',
            field=models.UUIDField(default=1, primary_key=True, serialize=False, verbose_name='二级分类id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secclassify',
            name='uid2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goodsapp.FirstClassify', verbose_name='所属一级分类'),
            preserve_default=False,
        ),
    ]
