# Generated by Django 2.0.1 on 2019-09-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0003_auto_20190910_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='secclassify',
            name='goods_img',
            field=models.CharField(max_length=200, null=True, verbose_name='商品图片'),
        ),
    ]
