# Generated by Django 2.0.1 on 2019-09-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0004_secclassify_goods_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secclassify',
            old_name='goods_img',
            new_name='img',
        ),
    ]
