# Generated by Django 2.0.1 on 2019-09-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopcartapp', '0001_initial'),
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsouseiMapModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('goods_id', models.ForeignKey(on_delete=True, to='goodsapp.GoodsModel', verbose_name='商品ID')),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcartapp.PictureModel')),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
                'db_table': 'app_carsouseimap',
            },
        ),
        migrations.CreateModel(
            name='NavigationDetaiModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModel', verbose_name='商品ID')),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcartapp.PictureModel')),
            ],
            options={
                'verbose_name': '导航详情表',
                'verbose_name_plural': '导航详情表',
                'db_table': 'app_navigationdetai',
            },
        ),
        migrations.CreateModel(
            name='SelectedModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcartapp.PictureModel')),
            ],
            options={
                'verbose_name': '精选推荐表',
                'verbose_name_plural': '精选推荐表',
                'db_table': 'app_selected',
            },
        ),
    ]
