# Generated by Django 2.0.1 on 2019-09-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexapp', '0001_initial'),
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='图片编号')),
                ('picture_name', models.CharField(max_length=30, verbose_name='图片名称')),
                ('picture_path', models.ImageField(height_field='picture_height', upload_to='picture', verbose_name='商品图片', width_field='picture_width')),
                ('picture_width', models.IntegerField(null=True, verbose_name='商品图片宽度')),
                ('picture_height', models.IntegerField(null=True, verbose_name='商品图片高度')),
            ],
            options={
                'verbose_name_plural': '图片表',
                'db_table': 'picture_table',
            },
        ),
        migrations.CreateModel(
            name='ShopCarModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='购物车编号')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('is_selected', models.BooleanField(default=True, verbose_name='是否选中')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModel', verbose_name='商品ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.UserModel', verbose_name='用户ID')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'car_table',
            },
        ),
    ]
