# Generated by Django 2.0.1 on 2019-09-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=500, verbose_name='评论详情')),
                ('time', models.DateTimeField(verbose_name='评论时间')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModel', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'app_user_detail',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('pwd', models.CharField(max_length=100, verbose_name='密码')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='users', verbose_name='用户图像')),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='余额')),
                ('level', models.IntegerField(choices=[(0, '青铜'), (1, '白银'), (2, '黄金')], default=0, verbose_name='用户级别')),
                ('is_life', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_rm', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='ViceCommentModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500, verbose_name='评论内容')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.UserCommentModel', verbose_name='评论ID')),
            ],
            options={
                'verbose_name': '用户评论副表',
                'verbose_name_plural': '用户评论副表',
                'db_table': 'app_user_detail_fu',
            },
        ),
        migrations.AddField(
            model_name='usercommentmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.UserModel', verbose_name='用户ID'),
        ),
    ]
