# Generated by Django 2.0.1 on 2019-09-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='用户图像'),
        ),
    ]
