# Generated by Django 2.0.1 on 2019-09-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexapp', '0001_initial'),
        ('goodsapp', '0001_initial'),
        ('addressapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(verbose_name='商品数量')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModel', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'app_orderdetail',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('total', models.FloatField(verbose_name='总价格')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='下单时间')),
                ('order_status', models.IntegerField(choices=[(1, '已下单'), (2, '已支付'), (3, '已发货'), (4, '已收货'), (5, '已完成'), (0, '已取消')], verbose_name='订单状态')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressapp.AddressModel', verbose_name='地址ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.UserModel', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
                'db_table': 'app_order',
            },
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单ID'),
        ),
    ]
