# Generated by Django 2.0.1 on 2019-09-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0006_auto_20190910_1706'),
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='goods_id',
        ),
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='total',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品数量'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='goods_id',
            field=models.ForeignKey(default='0017265345794178be430e8e3b9c86cc', on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModel', verbose_name='商品ID'),
        ),
        migrations.DeleteModel(
            name='OrderDetailModel',
        ),
    ]
