# Generated by Django 2.0.1 on 2019-09-11 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20190911_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModel', verbose_name='商品ID'),
        ),
    ]
